[project]
name = "url-shortner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.141.1",
    "hiredis>=3.4.0",
    "httpx2>=2.9.1",
    "pydantic-settings>=2.14.2",
    "redis>=8.0.1",
    "sqlmodel>=0.0.39",
    "streamlit>=1.60.0",
    "tzdata>=2026.3",
    "uvicorn>=0.52.0",
]

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.1",
    "typos>=1.49.0",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true

[tool.ruff.format]
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ['-p', 'no:warnings', '--cov=app', '--cov-context=test']

[tool.poe.tasks]
lint.sequence = [
    { cmd = "typos" },
    { cmd = "ruff check"},
]
format.sequence = [
    { cmd = "ruff check --fix" },
    { cmd = "ruff format" }
]
test.sequence = [
    { cmd = "pytest -s -x -vv $POE_EXTRA_ARGS" },
    { cmd = "coverage html --show-contexts" },
]

[tool.poe.tasks.serve]
parallel = [
    { cmd = "fastapi dev ./app/main.py" },
    { cmd = "streamlit run ./frontend/app.py --server.address=0.0.0.0 --server.port=8501" }
]

[tool.poe]
poetry_command = ""

[tool.typos.files]
extend-exclude = ['*.md']
